spring:
  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    url: jdbc:h2:~/h2db/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: admin
  sql:
    init:
      encoding: UTF-8
      mode: always
      schema-locations:
      - classpath:sql/schema.sql
      data-locations:
      - classpath:sql/data.sql
  h2:
    console:
      enabled: true